#!/bin/sh
set -e
# Automatically added by dh_installinit/12.10ubuntu1
if [ "$1" = "purge" ] ; then
	update-rc.d plcultimad remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_systemd_start/12.10ubuntu1
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_start/12.10ubuntu1
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/12.10ubuntu1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'plcultimad.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'plcultimad.service' >/dev/null || true
		deb-systemd-helper unmask 'plcultimad.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_systemd_enable/12.10ubuntu1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'plcultimad.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'plcultimad.service' >/dev/null || true
		deb-systemd-helper unmask 'plcultimad.service' >/dev/null || true
	fi
fi
# End automatically added section
